# Use the official Node.js image
FROM node:16-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY ./frontend/robot_dashboard/package.json ./frontend/robot_dashboard/package-lock.json ./

# Install dependencies
RUN npm install

# Copy the frontend code
COPY ./frontend/robot_dashboard /app

# Expose the port
EXPOSE 3000

# Start the application
CMD ["npm", "start"]
